In [8]:
#Crea una matrice 3x3 con valori compresi tra 0 e 8
import numpy as np
first_array = np.arange(9).reshape(3,3)
first_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [2]:
#Crea un vettore random con 30 elementi e trova il valore medio
import numpy as np
v = np.random.random((3,10))
print(v)
v.mean()

[[0.73776124 0.82673754 0.23800002 0.86412186 0.75927361 0.21554435
  0.35742448 0.99387137 0.98511033 0.04369211]
 [0.23240543 0.54646035 0.17077516 0.59265889 0.79061106 0.91762083
  0.70064527 0.5400729  0.14189894 0.21297408]
 [0.46642958 0.27799504 0.43148006 0.34734809 0.51475353 0.61459752
  0.594598   0.13356953 0.16684372 0.05004539]]


0.48217734239033144

In [7]:
#Trova gli indici degli elementi diversi da zero del seguente array [3,5,0,4,0,8,0]
import numpy as np
v = np.array([3,5,0,4,0,8,0])
print(np.where(v!=0))

#oppure

print(np.nonzero(v))

(array([0, 1, 3, 5], dtype=int64),)
(array([0, 1, 3, 5], dtype=int64),)


In [24]:
#Scrivi un programma per ottenere gli indici degli elementi ordinati di un dato array
import numpy as np
v = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print(np.argsort(v))

[0 3 4 6 1 5 2]


In [4]:
#Scrivi un programma che calcola la media attraverso la dimensione, in un array 2D(media di ogni colonna, media di ogni riga)
import numpy as np
m = np.arange(6, 30).reshape(6,4)
print(m)
print(m.mean(axis=1))     
print(m.mean(axis=0))


[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]
[ 7.5 11.5 15.5 19.5 23.5 27.5]
[16. 17. 18. 19.]
